name: Generate Languages

on:
  pull_request_target:
    branches:
    - dev
    paths:
    - i18n/languages/*.json
  push:
    branches:
    - dev
    paths:
    - i18n/languages/*.json
  workflow_dispatch:
  
jobs:
  generate_languages:
    name: Generate Languages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
        if: github.event_name == 'pull_request'
        
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.TOKEN }}
        if: github.event_name != 'pull_request'
          
      - name: Generate Languages
        run: ./generate-languages.ps1
        shell: pwsh
        
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Generated Languages"
